# Generated by Django 5.2.17 on 2026-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target',
            field=models.CharField(blank=True, help_text='The entity affected, e.g., Booking #123', max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
