# Generated by Django 5.2.17 on 2026-09-05 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialday',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_days', to='locations.businesslocation'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='locations.businesslocation'),
        ),
        migrations.AddField(
            model_name='breaktime',
            name='working_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='businesses.workingday'),
        ),
        migrations.AlterUniqueTogether(
            name='workingday',
            unique_together={('location', 'day_of_week')},
        ),
    ]
