# Generated by Django 5.2.17 on 2026-09-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_average_rating_business_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='brand_color',
            field=models.CharField(default='#000000', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='business',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='e.g. www.abc.com', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text="Store links like {'facebook': '...', 'instagram': '...'}"),
        ),
        migrations.AddField(
            model_name='business',
            name='subdomain',
            field=models.CharField(blank=True, help_text='e.g. abc for abc.bookinghai.in', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='booking_rules',
            field=models.TextField(blank=True, help_text='General rules for booking'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='Cancellation policy details'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed notification settings'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='push_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='whatsapp_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
