# Generated by Django 5.2.17 on 2026-09-05 16:31

import django.db.models.deletion
import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_business_average_rating_business_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=marketing.models.generate_code, max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=10)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=100)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='businesses.business')),
            ],
        ),
    ]
