# Generated by Django 5.2.17 on 2026-09-05 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_branches', models.IntegerField(default=1)),
                ('max_staff', models.IntegerField(default=1)),
                ('max_monthly_bookings', models.IntegerField(default=50)),
                ('has_premium_features', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('renewal_date', models.DateField()),
                ('current_billing_cycle_bookings', models.IntegerField(default=0)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='businesses.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
