# Generated by Django 5.2.17 on 2026-09-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_business_average_rating_business_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_event', models.CharField(choices=[('appt_confirmed', 'Appointment Confirmed'), ('appt_cancelled', 'Appointment Cancelled'), ('appt_missed', 'Appointment Missed'), ('24h_before', '24 Hours Before Appointment')], max_length=50)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('notify_owner', 'Notify Owner'), ('suggest_reschedule', 'Suggest Reschedule')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='businesses.business')),
            ],
        ),
    ]
